### PR TITLE
Use either ExampleScreenCapturer or TVIScreenCapturer

### PR DESCRIPTION
**Pull request by ceaglest**
Implemented as a view controller bool which can be flipped to use `TVIScreenCapturer` instead of the example. Another option would be to add a new target to the project which is setup to choose the SDK capturer.

TODO
* [x] Update readme instructions

### CODE REVIEW

**Comment by ptankTwilio** [comment]
I would recommend renaming `CustomScreenCapturerExample` to `ScreenCapturerExample`. So it would be like,  `ScreenCapturerExample` will demonstrate use of `TVIScreenCapturer` by default. User can use `ExampleScreenCapturer` by the boolean you have added if they want to use custom capturer.

**Comment by ptankTwilio** [comment]
Please update the main quick start README as well.

**Comment by ceaglest** [comment]
@ptankTwilio @paynerc I updated the PR based upon your feedback.

* Renamed `CustomScreenCapturerExample` to `ScreenCapturerExample`
* Choose TVIScreenCapturer by default
* Update documentation to reflect the change

**Comment by ptankTwilio** [comment]
👍

**Pull request merged**
